2024-08-13 01:28:41,515 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:28:41,516 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:28:41,786 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:28:41,821 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:28:43,379 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
2024-08-13 01:29:53,603 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:29:53,603 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:29:53,861 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:29:53,890 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:29:55,443 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
2024-08-13 01:31:04,573 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:31:04,574 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:31:04,834 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:31:04,863 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:31:06,422 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
2024-08-13 01:38:36,109 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:38:36,109 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:38:36,383 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:38:36,425 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:38:37,991 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
2024-08-13 01:49:15,966 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:49:15,967 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:49:16,296 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:49:16,336 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:49:17,910 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
2024-08-13 01:55:12,957 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:55:12,958 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:55:13,256 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:55:13,301 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:55:14,872 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 136, in load_data_csv
    data_id = row["ID"]
KeyError: 'ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 139, in load_data_csv
    raise KeyError(
KeyError: "CSV has to have an 'ID' field, with unique ids for all data points"
2024-08-13 01:59:45,440 - speechbrain.core - INFO - Beginning experiment!
2024-08-13 01:59:45,440 - speechbrain.core - INFO - Experiment folder: results/S2S/conmambamamba_L_S2S/3407
2024-08-13 01:59:45,714 - speechbrain.utils.superpowers - DEBUG - audioread==3.0.1
causal-conv1d==1.4.0
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
einops==0.8.0
filelock==3.13.1
fsspec==2024.2.0
gitdb==4.0.11
GitPython==3.1.43
huggingface-hub==0.24.5
HyperPyYAML==1.2.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.2
lazy_loader==0.4
librosa==0.10.2.post1
llvmlite==0.43.0
mamba-ssm==2.2.2
MarkupSafe==2.1.5
mpmath==1.3.0
msgpack==1.0.8
networkx==3.2.1
ninja==1.11.1.1
numba==0.60.0
numpy==2.0.1
nvidia-cublas-cu12==12.4.2.65
nvidia-cuda-cupti-cu12==12.4.99
nvidia-cuda-nvrtc-cu12==12.4.99
nvidia-cuda-runtime-cu12==12.4.99
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.0.44
nvidia-curand-cu12==10.3.5.119
nvidia-cusolver-cu12==11.6.0.99
nvidia-cusparse-cu12==12.3.0.142
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.4.99
packaging==24.1
pillow==10.4.0
platformdirs==4.2.2
pooch==1.8.2
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.13.1
sentencepiece==0.2.0
sentry-sdk==2.12.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
soundfile==0.12.1
sox==1.5.0
soxr==0.4.0
speechbrain==1.0.0
sympy==1.12
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0
tqdm==4.66.5
transformers==4.44.0
triton==3.0.0
typing_extensions==4.9.0
urllib3==2.2.2
wandb==0.17.6


2024-08-13 01:59:45,752 - speechbrain.utils.superpowers - DEBUG - 07c51ab


2024-08-13 01:59:47,301 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 425, in <module>
    ) = dataio_prepare(hparams)
  File "/mnt/Work/VSCODE/Mamba-ASR/train_S2S.py", line 257, in dataio_prepare
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/tfmhitesh/.conda/envs/Slytherin/lib/python3.9/site-packages/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'
